apiVersion: apps/v1
kind: Deployment
metadata:
  name: fauldeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-exp
  template:
    metadata:
      labels:
        app: first-exp
    spec:
      containers:
      - name: web
        image: lewisferreira/conversao-temperatura:v1
        ports:
          - containerPort: 8080
