apiVersion: v1
kind: Pod
metadata:
  name: faulpod
  labels:
    app: web
spec:
  containers:
  - name: web
    image: fabricioveronez/conversao-temperatura:v1
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 8080
