apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: faulreplicaset
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: lewisferreira/conversao-temperatura:v1
        ports:
          - containerPort: 8080
