apiVersion: v1
kind: Service
metadata:
  name: faulservice
spec:
  selector:
    app: first-exp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
